format = """ 
\
$os\
$username\
$directory\
$git_branch\
$git_status\
$all\
$character"""

[username]
show_always = true
format = '[$user ]($style)'
style_user = "white bold"
disabled = true

[os]
disabled = false
style = 'cyan'

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
AlmaLinux = "ïŒ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CachyOS = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Kali = "ïŒ§ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
Nobara = "ï€ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
RockyLinux = "ïŒ« "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Void = "ïŒ® "
Windows = "ó°² "

[cmd_duration]
format = "[$duration]($style) "
style="white bold"

[character]
success_symbol = "[ï‘ ](bold blue)"
error_symbol = "[âœ—](bold red)"
disabled = false

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 2
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ó°š "
"Pictures" = "ï€¾ "
"Scripts" = "ó°²‹ "

[hostname]
ssh_symbol = "î¬ "
format = '[$ssh_symbol$hostname]($style) '

[fossil_branch]
symbol = "ï˜ "
format = '[$symbol$branch]($style) '

[hg_branch]
symbol = "ï˜ "
format = '[$symbol$branch(:$topic)]($style) '

[pijul_channel]
symbol = "ï˜ "
format = '[$symbol$channel]($style) '

[git_branch]
symbol = "ï˜ "
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_commit]
tag_symbol = 'ï’ '
format = '[\($hash$tag\)]($style) '

# Langs and stuff

[custom.ada]
symbol = "Ada "
style = 'bold yellow'
format = '[$symbol($output)]($style) '
detect_extensions = [ 'ada', 'adc', 'ads', 'adb' ]
command = "gnatmake --version 2>/dev/null | sed -n 's/.*GNATMAKE[ \\t]*\\([0-9.]*\\).*/\\1-gnat/p'"
disabled = false

[aws]
symbol = "ó°¸ "
format = '[$symbol($profile)( \($region\))( \[$duration\])]($style) '
disabled = false

[buf]
symbol = "ï’ "
format = '[$symbol($version)]($style) '
disabled = false

[bun]
symbol = "î¯ "
format = '[$symbol($version)]($style) '
disabled = false

[c]
symbol = "î˜ "
format = '[$symbol($version(-$name))]($style) '
disabled = false

[custom.c3]
symbol = "C3 "
style = 'bold blue'
format = '[$symbol($output)]($style) '
detect_extensions = [ 'c3' ]
command = "c3c --version 2>/dev/null | sed -n 's/.*C3 Compiler Version:[ \\t]*\\([0-9.]*\\).*/\\1/p'"
disabled = false

[cpp]
symbol = "î™† "
format = '[$symbol($version(-$name))]($style) '
disabled = false
style = 'bold blue'

[cmake]
symbol = "â–³ "
format = '[$symbol($version)]($style) '
disabled = false

[cobol]
symbol = "ó°’“ "
format = '[$symbol($version)]($style) '
disabled = false

[conda]
symbol = "ğŸ…’ "
format = '[$symbol$environment]($style) '
disabled = false

[container]
symbol = "â¬¢ "
format = '[$symbol \[$name\]]($style) '
disabled = false

[crystal]
symbol = "î˜¯ "
format = '[$symbol($version)]($style) '
disabled = false

[daml]
symbol = "Î› "
format = '[$symbol($version)]($style) '
disabled = false

[dart]
symbol = "î˜ "
format = '[$symbol($version)]($style) '
disabled = false

[deno]
symbol = "îŸ€ "
format = '[$symbol($version)]($style) '
disabled = false

[direnv]
symbol = "ï• "
format = '[$symbol$loaded/$allowed]($style) '
disabled = false

[docker_context]
symbol = "ïŒˆ "
format = '[$symbol$context]($style) '
disabled = false

[dotnet]
symbol = ".NET "
format = '[$symbol($version)($tfm)]($style) '
detect_files = ['global.json', 'Directory.Build.props', 'Directory.Build.targets', 'Packages.props']
disabled = false

[elixir]
symbol = "î˜­ "
format = '[$symbol($version \(OTP $otp_version\))]($style) '
disabled = false

[elm]
symbol = "î˜¬ "
format = '[$symbol($version)]($style) '
disabled = false

[erlang]
symbol = "î± "
format = '[$symbol($version)]($style) '
disabled = false

[fennel]
symbol = "îš¯ "
format = '[$symbol($version)]($style) '
disabled = false

[gleam]
symbol = "ï€… "
format = '[$symbol($version)]($style) '
disabled = false

[golang]
symbol = "î˜§ "
format = '[$symbol($version)]($style) '
disabled = false

[guix_shell]
symbol = "ïŒ¥ "
format = '[$symbol]($style) '
disabled = false

[gradle]
symbol = "î™  "
format = '[$symbol($version)]($style) '
disabled = false

[haskell]
symbol = "Î» "
format = '[$symbol($version)]($style) '
disabled = false

[haxe]
symbol = "î™¦ "
format = '[$symbol($version)]($style) '
disabled = false

[helm]
symbol = "âˆ "
format = '[$symbol($version)]($style) '
disabled = false

[java]
symbol = "î¶¯ "
style = 'red bold'
format = '[$symbol($version)]($style) '
detect_extensions = ['java', 'class', 'gradle', 'jar', 'cljs', 'cljc', 'kt', 'kts']
disabled = false

[julia]
symbol = "î˜¤ "
format = '[$symbol($version)]($style) '
disabled = false

[kotlin]
symbol = "î˜´ "
format = '[$symbol($version)]($style) '
disabled = false

[kubernetes]
symbol = "â˜¸ "
format = '[$symbol$context( \($namespace\))]($style) '
disabled = false

[lua]
symbol = "î˜  "
format = '[$symbol($version)]($style) '
disabled = false

[meson]
symbol = "â¬¢ "
format = '[$symbol$project]($style) '
disabled = false

[mise]
symbol = "mise "
format = '[$symbol$health]($style) '
disabled = false

[mojo]
symbol = "ğŸ”¥ "
format = '[$symbol($version)]($style) '
disabled = false

[nats]
symbol = "ó°¾± "
format = '[$symbol$name]($style) '
disabled = false

[nim]
symbol = "ó°†¥ "
format = '[$symbol($version)]($style) '
disabled = false

[nix_shell]
symbol = "ïŒ“ "
format = '[$symbol$state( \($name\))]($style) '
disabled = false

[nodejs]
symbol = "îœ˜ "
format = '[$symbol($version)]($style) '
disabled = false

[ocaml]
symbol = "î™º "
format = '[$symbol($version)( \($switch_indicator$switch_name\))]($style) '
disabled = false

[odin]
symbol = "Ã˜ "
format = '[$symbol($version)]($style) '
disabled = false

[openstack]
symbol = "î¡– "
format = '[$symbol$cloud(\($project\))]($style) '
disabled = false

[package]
symbol = "ó°— "
format = '[$symbol($version)]($style) '
disabled = false

[perl]
symbol = "î™¾ "
format = '[$symbol($version)]($style) '
disabled = false

[php]
symbol = "î˜ˆ "
format = '[$symbol($version)]($style) '
disabled = false

[pixi]
symbol = "ó±¡„ "
format = '[$symbol($version)]($style) '
disabled = false

[pulumi]
symbol = "ï†² "
format = '[$symbol($username@)$stack]($style) '
disabled = false

[purescript]
symbol = "<=> "
format = '[$symbol($version)]($style) '
disabled = false

[python]
symbol = "îˆµ "
style = 'bold green'
format = '[${symbol}${pyenv_prefix}(${version})( \($virtualenv\))]($style) '
disabled = false

[quarto]
symbol = "â¨ "
format = '[$symbol($version)]($style) '
disabled = false

[rlang]
symbol = "îˆ› "
format = '[$symbol($version)]($style) '
disabled = false

[raku]
symbol = "ó±–‰ "
format = '[$symbol($version-$vm_version)]($style) '
disabled = false

[red]
symbol = "ó°”¶ "
format = '[$symbol($version)]($style) '
disabled = false

[ruby]
symbol = "î‘ "
format = '[$symbol($version)]($style) '
disabled = false

[rust]
symbol = "ó±˜— "
format = '[$symbol($version)]($style) '
disabled = false

[scala]
symbol = "îœ· "
format = '[$symbol($version)]($style) '
disabled = false

[singularity]
symbol = "î° "
format = '[$symbol\[$env\]]($style) '
disabled = false

[solidity]
symbol = "S "
format = '[$symbol($version)]($style) '
disabled = false

[spack]
symbol = "î• "
format = '[$symbol$environment]($style) '
disabled = false

[swift]
symbol = "î• "
format = '[$symbol($version)]($style) '
disabled = false

[terraform]
symbol = "î¢½ "
format = '[$symbol$workspace]($style) '
disabled = false

[typst]
symbol = "t "
format = '[$symbol($version)]($style) '
disabled = false

[vagrant]
symbol = "â± "
format = '[$symbol($version)]($style) '
disabled = false

[vlang]
symbol = "V "
format = '[$symbol($version)]($style) '
disabled = false

[zig]
symbol = "îš© "
format = '[$symbol($version)]($style) '
disabled = false